run2:
	flex tp3.l
	gcc -o tp3 lex.yy.c -I /usr/local/include/graphviz/
	./tp3 ${ARGS} < ../lib2.bib 

run1:
	flex tp3.l
	gcc -o tp3 lex.yy.c -I /usr/local/include/graphviz/
	./tp3 ${ARGS} < ../lib.bib  

